In [1]:
import torch

In [2]:
def activation(x):
    return 1 / (1 + torch.exp(-x))

In [3]:
torch.manual_seed(10)
features = torch.randn(1,5)
weights = torch.rand_like(features)
bias = torch.randn(1,1)

In [7]:
weights.resize_(5,1)

tensor([[0.7041],
        [0.5573],
        [0.6959],
        [0.9849],
        [0.2924]])

In [9]:
activation(torch.matmul(features, weights.resize(5,1)) + bias)

tensor([[0.0768]])

In [43]:
#generate some data
torch.manual_seed(7)


#features are 3 RV
features = torch.randn(1,3)

#define the size of each layer in our network
n_input = features.shape[1]
n_hidden = 2
n_output = 1

# Weights for inputs to hidden layer
w1 = torch.randn(n_input, n_hidden)

# Weights for hidden layer to output layer
w2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
b1 = torch.randn(1,n_hidden)
b2 = torch.randn(1,n_output)

In [46]:
h1 = activation(torch.matmul(features, w1[:,0].resize(3,1)) + b1[:,0])
h2 = activation(torch.matmul(features, w1[:,1].resize(3,1)) + b1[:,1])

h = torch.cat((h1, h2),1)

out = activation(torch.matmul(h, w2) + b2)
out

tensor([[0.3171]])

In [47]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.05209446, 0.1656795 , 0.19808654],
       [0.02628809, 0.95959754, 0.90346633],
       [0.69514908, 0.97074867, 0.63619071],
       [0.6712695 , 0.85583705, 0.81088896]])

In [48]:
b = torch.from_numpy(a)
b

tensor([[0.0521, 0.1657, 0.1981],
        [0.0263, 0.9596, 0.9035],
        [0.6951, 0.9707, 0.6362],
        [0.6713, 0.8558, 0.8109]], dtype=torch.float64)

In [49]:
b.numpy()

array([[0.05209446, 0.1656795 , 0.19808654],
       [0.02628809, 0.95959754, 0.90346633],
       [0.69514908, 0.97074867, 0.63619071],
       [0.6712695 , 0.85583705, 0.81088896]])

In [50]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[0.1042, 0.3314, 0.3962],
        [0.0526, 1.9192, 1.8069],
        [1.3903, 1.9415, 1.2724],
        [1.3425, 1.7117, 1.6218]], dtype=torch.float64)

In [51]:
# Numpy array matches new values from Tensor
a

array([[0.10418891, 0.331359  , 0.39617308],
       [0.05257618, 1.91919509, 1.80693266],
       [1.39029816, 1.94149733, 1.27238141],
       [1.342539  , 1.71167409, 1.62177792]])